# Generated by Django 5.0.14 on 2025-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamuser',
            name='desktop_ip',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
