# Generated by Django 5.0.14 on 2025-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbot', '0002_gamuser_desktop_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamuser',
            name='desktop_ip',
            field=models.CharField(max_length=255),
        ),
    ]
