# Generated by Django 5.0.14 on 2025-05-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbot', '0003_alter_gamuser_desktop_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
