# Generated by Django 5.0.14 on 2025-05-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_summaryletter_delete_lettermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryletter',
            name='subject',
        ),
    ]
