# Generated by Django 5.0.14 on 2025-06-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbot', '0005_gamuser_user'),
        ('letters', '0004_summaryletter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryletter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botbot.gamuser'),
        ),
    ]
