# Generated by Django 5.0.14 on 2025-06-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_letterarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterarchive',
            name='letter_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='letterarchive',
            name='sent_time',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
